"use client";

import { useState } from "react";
import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { getInventoryItems, InventoryItem } from "@/lib/api/inventory-client";
import { createInvoice, Invoice } from "@/lib/api/invoice-client";
import { createPayment } from "@/lib/api/payments";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import {
  Search,
  ShoppingCart,
  Plus,
  Minus,
  Trash2,
  CreditCard,
} from "lucide-react";
import { toast } from "sonner";
import { Separator } from "@/components/ui/separator";
import { Badge } from "@/components/ui/badge";
import { ScrollArea } from "@/components/ui/scroll-area";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { Label } from "@/components/ui/label";

interface CartItem extends InventoryItem {
  quantity: number;
}

export default function QuickSaleClient() {
  const [search, setSearch] = useState("");
  const [cart, setCart] = useState<CartItem[]>([]);
  const [paymentMethod, setPaymentMethod] = useState("cash");
  const [customerName, setCustomerName] = useState("");
  const queryClient = useQueryClient();

  const { data: inventoryData, isLoading } = useQuery<InventoryItem[]>({
    queryKey: ["inventory", search],
    queryFn: () => getInventoryItems({ search, active: true, limit: 50 }),
  });

  const createSaleMutation = useMutation({
    mutationFn: async (): Promise<{
      invoice: Invoice;
      totalAmount: number;
    }> => {
      // Create Invoice with Inventory Items
      // Note: API should handle stock decrement and payment creation if needed?
      // Actually, implementation plan said "Create Invoice (status: paid), Decrement Stock, Create Payment"
      // But my InvoicesService.create handles creation.
      // Wait, InvoicesService.create sets status to 'partial' by default, or calculates it?
      // It recalculates. If I don't send payments, it will be partial/unpaid.
      // I need to send payments?
      // My update to InvoicesService.create didn't add payment creation logic in one go,
      // but `createOnvoiceDto` might have payments? No, schema doesn't usually allow creating payments nested in invoice create easily unless I updated DTO.
      // Let's check `CreateInvoiceDto`.

      // Actually, standard flow: Create Invoice -> Create Payment.
      // But for POS, we want atomic?
      // If I create invoice first, stock is decremented.
      // Then I create payment immediately.

      // Step 1: Create Invoice
      // Flatten cart into individual unit lines
      const flatLineItems = [];
      for (const item of cart) {
        for (let i = 0; i < item.quantity; i++) {
          flatLineItems.push({
            inventoryItemId: item.id,
            description: item.name, // maybe append (1/2)? No, just distinct lines is fine.
            amount: Number(item.price),
          });
        }
      }

      const subtotal = flatLineItems.reduce(
        (sum, item) => sum + item.amount,
        0,
      );

      const taxRate = paymentMethod === "cash" ? 0 : 0.13;
      const taxAmount = subtotal * taxRate;
      const totalAmount = subtotal + taxAmount;

      if (taxAmount > 0) {
        flatLineItems.push({
          inventoryItemId: undefined, // Tax is not an inventory item
          description: "HST (13%)",
          amount: taxAmount,
        });
      }

      const invoice = await createInvoice({
        lineItems: flatLineItems,
        totalAmount: totalAmount,
        notes: customerName ? `Guest: ${customerName}` : "POS Sale",
        // invoiceNumber will be auto-generated by backend
      });

      // Step 2: Pay it
      // I need a `createPayment` function. I haven't imported it.
      // Let's fetch it via API client if available.
      // Assuming `createPayment` exists in `@/lib/api/payments-client` or similar.
      // If not, I'll have to rely on invoice being unpaid first?
      // Ideally POS is paid.
      // I'll assume I can add payment logic here.

      // Actually, let's use a specialized endpoint if possible?
      // No, plan said "Update InvoicesService.create".
      // So I'll do two queries.

      return { invoice, totalAmount };
    },
    onSuccess: async ({
      invoice,
      totalAmount,
    }: {
      invoice: Invoice;
      totalAmount: number;
    }) => {
      // Now create payment
      try {
        await createPayment({
          invoiceId: invoice.id,
          amount: totalAmount,
          paymentDate: new Date().toISOString(),
          paymentMethod: paymentMethod,
          notes: "POS Transaction",
        });

        toast.success(
          `Sale completed! Invoice #${invoice.invoiceNumber} created.`,
        );
        setCart([]);
        setCustomerName("");
        queryClient.invalidateQueries({ queryKey: ["inventory"] });
        queryClient.invalidateQueries({ queryKey: ["invoices"] });
      } catch (e) {
        console.error(e);
        toast.error("Invoice created but payment failed");
      }
    },
    onError: () => {
      toast.error("Transaction failed");
    },
  });

  const addToCart = (item: InventoryItem) => {
    setCart((prev) => {
      const existing = prev.find((i) => i.id === item.id);
      if (existing) {
        if (existing.quantity >= item.stock) {
          toast.error("Not enough stock");
          return prev;
        }
        return prev.map((i) =>
          i.id === item.id ? { ...i, quantity: i.quantity + 1 } : i,
        );
      }
      return [...prev, { ...item, quantity: 1 }];
    });
  };

  const removeFromCart = (itemId: string) => {
    setCart((prev) => prev.filter((i) => i.id !== itemId));
  };

  const updateQuantity = (itemId: string, delta: number) => {
    setCart((prev) => {
      return prev.map((i) => {
        if (i.id === itemId) {
          const newQ = i.quantity + delta;
          if (newQ < 1) return i;
          // Check stock
          const itemData = inventoryData?.find(
            (d: InventoryItem) => d.id === itemId,
          );
          if (itemData && newQ > itemData.stock) {
            toast.error("Max stock reached");
            return i;
          }
          return { ...i, quantity: newQ };
        }
        return i;
      });
    });
  };

  const cartTotal = cart.reduce(
    (sum, item) => sum + item.price * item.quantity,
    0,
  );

  return (
    <div className="flex flex-col lg:flex-row h-full gap-6">
      {/* Left: Product Catalog */}
      <div className="flex-1 space-y-4">
        <div className="flex items-center space-x-2 bg-white p-4 rounded-lg shadow-sm">
          <Search className="h-5 w-5 text-muted-foreground" />
          <Input
            placeholder="Search products..."
            className="border-none shadow-none focus-visible:ring-0 text-lg"
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            autoFocus
          />
        </div>

        <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">
          {isLoading ? (
            <p>Loading products...</p>
          ) : (
            inventoryData?.map((item: InventoryItem) => (
              <Card
                key={item.id}
                className={`cursor-pointer transition-all hover:shadow-md ${item.stock === 0 ? "opacity-50 pointer-events-none" : ""}`}
                onClick={() => addToCart(item)}
              >
                <CardHeader className="p-4 pb-2">
                  <CardTitle className="text-base truncate" title={item.name}>
                    {item.name}
                  </CardTitle>
                </CardHeader>
                <CardContent className="p-4 pt-0">
                  <div className="flex justify-between items-end">
                    <span className="font-bold text-lg">
                      ${Number(item.price).toFixed(2)}
                    </span>
                    <Badge
                      variant={item.stock > 0 ? "secondary" : "destructive"}
                      className="text-xs"
                    >
                      {item.stock} left
                    </Badge>
                  </div>
                  <div className="mt-2 text-xs text-muted-foreground truncate">
                    {item.sku}
                  </div>
                </CardContent>
              </Card>
            ))
          )}
        </div>
      </div>

      {/* Right: Cart */}
      <div className="w-full lg:w-[400px] flex flex-col h-[calc(100vh-120px)] sticky top-4">
        <Card className="flex-1 flex flex-col shadow-lg border-2">
          <CardHeader className="border-b bg-gray-50/50">
            <CardTitle className="flex items-center">
              <ShoppingCart className="mr-2 h-5 w-5" /> Current Sale
            </CardTitle>
          </CardHeader>
          <CardContent className="flex-1 overflow-hidden p-0">
            <ScrollArea className="h-full p-4">
              {cart.length === 0 ? (
                <div className="h-full flex flex-col items-center justify-center text-muted-foreground space-y-2 opacity-50">
                  <ShoppingCart className="h-12 w-12" />
                  <p>Cart is empty</p>
                </div>
              ) : (
                <div className="space-y-4">
                  {cart.map((item) => (
                    <div
                      key={item.id}
                      className="flex justify-between items-start group"
                    >
                      <div className="flex-1">
                        <div className="font-medium">{item.name}</div>
                        <div className="text-sm text-muted-foreground">
                          ${Number(item.price).toFixed(2)} x {item.quantity}
                        </div>
                      </div>
                      <div className="flex items-center space-x-2">
                        <div className="flex items-center border rounded-md">
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6 rounded-none"
                            onClick={() => updateQuantity(item.id, -1)}
                          >
                            <Minus className="h-3 w-3" />
                          </Button>
                          <span className="w-8 text-center text-sm">
                            {item.quantity}
                          </span>
                          <Button
                            variant="ghost"
                            size="icon"
                            className="h-6 w-6 rounded-none"
                            onClick={() => updateQuantity(item.id, 1)}
                          >
                            <Plus className="h-3 w-3" />
                          </Button>
                        </div>
                        <Button
                          variant="ghost"
                          size="icon"
                          className="h-6 w-6 text-destructive opacity-0 group-hover:opacity-100 transition-opacity"
                          onClick={() => removeFromCart(item.id)}
                        >
                          <Trash2 className="h-4 w-4" />
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </ScrollArea>
          </CardContent>

          <div className="p-4 bg-gray-50/50 border-t space-y-4">
            <div className="space-y-2">
              <Label>Customer (Optional)</Label>
              <Input
                placeholder="Guest Name"
                value={customerName}
                onChange={(e) => setCustomerName(e.target.value)}
                className="bg-white"
              />
            </div>
            <div className="space-y-2">
              <Label>Payment Method</Label>
              <Select value={paymentMethod} onValueChange={setPaymentMethod}>
                <SelectTrigger className="bg-white">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="cash">Cash</SelectItem>
                  <SelectItem value="debit">Debit</SelectItem>
                  <SelectItem value="visa">Visa</SelectItem>
                  <SelectItem value="mastercard">Mastercard</SelectItem>
                  <SelectItem value="etransfer">E-Transfer</SelectItem>
                </SelectContent>
              </Select>
            </div>

            <Separator />

            <div className="space-y-1">
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">Subtotal</span>
                <span>${cartTotal.toFixed(2)}</span>
              </div>
              <div className="flex justify-between text-sm">
                <span className="text-muted-foreground">
                  Tax {paymentMethod !== "cash" && "(13%)"}
                </span>
                <span>
                  $
                  {(paymentMethod === "cash" ? 0 : cartTotal * 0.13).toFixed(2)}
                </span>
              </div>
              <Separator className="my-2" />
              <div className="flex justify-between items-center text-lg font-bold">
                <span>Total</span>
                <span>
                  $
                  {(paymentMethod === "cash"
                    ? cartTotal
                    : cartTotal * 1.13
                  ).toFixed(2)}
                </span>
              </div>
            </div>

            <Button
              size="lg"
              className="w-full"
              disabled={cart.length === 0 || createSaleMutation.isPending}
              onClick={() => createSaleMutation.mutate()}
            >
              {createSaleMutation.isPending ? (
                "Processing..."
              ) : (
                <>
                  <CreditCard className="mr-2 h-5 w-5" /> Pay & Complete
                </>
              )}
            </Button>
          </div>
        </Card>
      </div>
    </div>
  );
}
